name: Republish Next.js site to Pages

# [Assign schedule on github action]
# (1) https://danielsaidi.com/blog/2022/05/11/schedule-github-pages-rebuild-with-github-actions
# (2) https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onschedule

on:
  schedule:
    - cron: '0 4,16 * * *' # Run at 4:00 am, 4:00 pm every day.
    #     *      *          *           *           *
    #  | min | hour | dayOfTheMonth | month | dayOfTheWeek |
jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger GitHub pages rebuild
        env:
          GH_USER_TOKEN: ${{ secrets.GH_USER_TOKEN }} # WARN: is this really needed?
        # execute workflow
        run: |
          gh workflow run nextjs.yml
